### ISSUE TITLE
Not compatybile with Varnish Cache

### ISSUE THREAD

**Issue by KamilBalwierz** [dotpay/Magento2#8]
We have tested this method on Varnish Cache enabled Magento2 instance placing two orders for different amounts one after another.
We expected to see two payments in dotpay panel with different amounts.
But we have seen two payments for first orders (both payments registered by dotpay have amount and Order ID of first order).

I assume that form with redirect to dotpay service is being cached in Varnish Cache.

**Comment by wpawel** [comment]
A new release has just been published v3.0.2 :
force blocking of HTTP headers caching
Please check if it works correctly for you.
